name: hsr-project
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - blosc=1.21.5=hc338f07_0
  - branca=0.7.0=pyhd8ed1ab_1
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py312h9f69965_1
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.23.0=h93a5062_0
  - ca-certificates=2023.11.17=hf0a4a13_0
  - cairo=1.18.0=hd1e100b_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cfitsio=4.3.1=h808cd33_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.2.0=py312h76e736e_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.0=py312h9f69965_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_1
  - fiona=1.9.5=py312hfe67d44_1
  - folium=0.15.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.46.0=py312he37b823_0
  - freetype=2.12.1=hadb7bae_2
  - freexl=2.0.0=hfbad9fb_0
  - gdal=3.8.1=py312hb8631af_1
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.14.1=pyhd8ed1ab_0
  - geopandas-base=0.14.1=pyha770c72_0
  - geopy=2.4.1=pyhd8ed1ab_0
  - geos=3.12.1=h965bd2d_0
  - geotiff=1.7.1=h71398c0_14
  - gettext=0.21.1=h0186832_0
  - giflib=5.2.1=h1a8c8d9_3
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.2=nompi_h3aba7b3_100
  - icu=73.2=hc8870d7_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.26.0=pyh3cd1d5f_0
  - ipython=8.18.1=pyh31011fe_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - json-c=0.17=h40ed0f5_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py312h81bd7bf_0
  - kealib=1.5.2=h47b5e36_1
  - kiwisolver=1.4.5=py312h389731b_1
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libaec=1.1.2=h13dd4ca_1
  - libarchive=3.7.2=h82b9b87_0
  - libblas=3.9.0=20_osxarm64_openblas
  - libboost-headers=1.83.0=hce30654_0
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=20_osxarm64_openblas
  - libcurl=8.4.0=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.19=hb547adb_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libgdal=3.8.1=hac00559_1
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libglib=2.78.1=hb438215_1
  - libiconv=1.17=he4db4b2_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - libkml=1.3.0=h1eb4d9f_1018
  - liblapack=3.9.0=20_osxarm64_openblas
  - libnetcdf=4.9.2=nompi_hb2fb864_112
  - libnghttp2=1.58.0=ha4dd798_0
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libpng=1.6.39=h76d750c_0
  - libpq=16.1=hd435d45_2
  - librttopo=1.1.0=hc8f776e_15
  - libsodium=1.0.18=h27ca646_1
  - libspatialindex=1.9.3=hbdafb3b_4
  - libspatialite=5.1.0=h66af7d6_2
  - libsqlite=3.44.2=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtiff=4.6.0=ha8a6c65_2
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.11.6=h0d0cfa8_0
  - libzip=1.10.1=ha0bc3c6_3
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=17.0.6=hcd81f8e_0
  - lz4-c=1.9.4=hb7217d7_0
  - lzo=2.10=h642e427_1000
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markupsafe=2.1.3=py312h02f2b3b_1
  - matplotlib-base=3.8.2=py312hba9b818_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - minizip=4.0.3=hd5cad61_0
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h463b476_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nspr=4.35=hb7217d7_0
  - nss=3.95=h6cf673f_0
  - numpy=1.26.2=py312h5d55045_0
  - openjpeg=2.5.0=h4c1507b_3
  - openssl=3.2.0=h0d3ecfb_1
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.3=py312h9e53831_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.42=h26f9a81_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.1.0=py312hac22aec_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h13dd4ca_0
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - poppler=23.12.0=hcdd998b_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.1=hc6ab77f_2
  - proj=9.3.0=h52fb9d0_2
  - prompt-toolkit=3.0.41=pyha770c72_0
  - psutil=5.9.5=py312h02f2b3b_1
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproj=3.6.1=py312h33684bb_4
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.0=h47c9636_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyzmq=25.1.1=py312h2105c20_2
  - readline=8.2=h92ec313_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rtree=1.1.0=py312h22f7183_0
  - scikit-learn=1.3.2=py312h6f466fd_1
  - scipy=1.11.4=py312h510ce61_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shapely=2.0.2=py312h04e4829_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h17c5cce_0
  - sqlite=3.44.2=hf2abe2d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tiledb=2.16.3=hc77a09f_3
  - tk=8.6.13=h5083fa2_1
  - tornado=6.3.3=py312h02f2b3b_1
  - traitlets=5.14.0=pyhd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzcode=2023c=h1a8c8d9_0
  - tzdata=2023c=h71feb2d_0
  - uriparser=0.9.7=hb7217d7_1
  - urllib3=2.1.0=pyhd8ed1ab_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xerces-c=3.2.4=hd886eac_3
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.5=h965bd2d_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=h4f39d0f_0
